config/routes.rb
Rails.application.routes.draw do
  root to: 'surveys#index'

  resources :users
  resources :surveys do
    # note on `path:` option:
    # we want SurveyResponse as the domain object, but our path to be survey/:survey_id/responses
    # note on our `as:` option:
    # this makes our helpers readable (eg survey_responses instead of survey_survey_responses for the index path)
    resources :survey_responses, path: 'responses', as: :responses
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :user

  has_many :survey_responses, dependent: :destroy
  has_many :survey_question_responses, through: :survey_responses
  has_one :survey_question, dependent: :destroy

  accepts_nested_attributes_for :survey_question

  validates_presence_of :title, :survey_question

  # Next Iteration:
  # There is a better way to handle stats calculations like this
  # Either through a db trigger that updates a stats table (probably not, but it's possible)
  # Or through another datastore like that we can toss stats into the handle calculations
  # Mongodb comes to mind, I think you can have indexes on a mongo collection that calculate stats in the background
  def yes_percentage
    return nil unless survey_responses.any?
    BigDecimal(survey_question_responses.yes_responses.size) / BigDecimal(survey_responses.size) * BigDecimal(100)
  end

  def no_percentage
    return nil unless survey_responses.any?
    BigDecimal(100) - yes_percentage
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[ show edit update destroy responses]

  def index
    # Hoping to speed up our calculations for yes/no responses by preloading relevant survey_question_responses
    # To avoid this page from falling over we'd eventually want to select only the values we need from the models
    # as also paginate to avoid loading every record at the same time.
    @surveys = Survey.includes(survey_responses: :survey_question_response).all
  end

  def show
  end

  def new
    @survey = Survey.new(user_id: current_user.id)
    @survey.build_survey_question
  end

  def create
    @survey = current_user.surveys.build(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to surveys_url, notice: "Survey was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @survey.build_survey_question unless @survey.survey_question
  end

  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Survey was successfully deleted." }
    end
  end

  private

  def set_survey
    @survey = Survey.find(params[:id])
  end

  def survey_params
    params.require(:survey).permit(:title, survey_question_attributes: [ :content])
  end
end

app/views/surveys/_form.html.erb
<%= form_with model: survey, local: true do |form| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
        <% survey.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>


  <%= form.fields_for :survey_question do |question_form| %>
    <%= question_form.label :content, 'Yes/No Question' %>
    <%= question_form.text_field :content %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Question</th>
      <th></th>
      <th>Yes Response %</th>
      <th>No Response %</th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= link_to survey.title, new_survey_response_path(survey) %></td>
        <td><%= survey.survey_question.content %></td>
        <td><%= link_to 'List Responses', survey_responses_path(survey) %></td>
        <td><%= number_to_percentage(survey.yes_percentage, strip_insignificant_zeros: true) %></td>
        <td><%= number_to_percentage(survey.no_percentage, strip_insignificant_zeros: true) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/survey.html.erb
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', survey_path %>